### ISSUE TITLE
[New app]: Ccleaner and Defragler

### ISSUE THREAD

**Issue by hpmillaard** [aaronparker/evergreen#291]
### What is the new application?

These applications can be used to optimize your Windows installation

### Vendor site

https://ccleaner.com

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
Defragler doesn't have an update mechanism that can be piggy-backed on, so it's not suitable for Evergreen

**Comment by JonathanPitre** [comment]
Can we get the slim and portable versions? 
It may not be wise since they Piriform wrote this on their website but yet the downloads are available for anyone.
`Builds below are for system admins and advanced users. They are not for distribution or mirroring.`

https://www.ccleaner.com/ccleaner/builds

**Comment by aaronparker** [comment]
I haven't as yet.

Evergreen isn't distributing or mirroring those installers, it's just providing the URL, so I think we're safe.
